# Generated by Django 5.2.11 on 2026-02-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(null=True),
        ),
    ]
